spring:
  application:
    name: msapi
  jpa:
    hibernate:
      ddl-aut: update
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:api
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2-console
  backend:
    host: #host baco parceiro

#Subir em uma porta aleatoria.
#Ao se registra no eureka o loadbalacer com o gateway consiga mapear as portas aleatorias.
server:
  port: 0

#Se registrando no eureka.
eureka:
  client:
    servise-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#Gerando nome de instancia randomico

springdoc:
  swagger-ui:
    path: /index.html